tank      ("tanks.helium3",       14, 12)
tank      ("tanks.tritium",       33, 12)
tank      ("tanks.wolframium",    52, 12)
tank      ("tanks.lithium",       14, 18)
tank      ("tanks.deuterium",     33, 18)
tank      ("tanks.berylium",      52, 18)
tank      ("tanks.plasma",       123, 15)
tank_small("reactor.input_east",  80,  6, "Input East")
tank_small("reactor.input_west",  80, 24, "Input West")
production("reactor.recipe",      98, 19, "Producing")
me        ("item.helium3"         20, 26)
me        ("item.tritium"         20, 28)
me        ("item.deuterium"       20, 30)
me        ("item.lithium"         34, 26)
me        ("item.berylium"        26, 28)
me        ("item.wolframium"      28, 30)
me        ("item.cells"           56, 49)
me        ("item.hydrogen"        86, 49)
me        ("item.iridium"        126, 23)
me        ("item.platinum"       126, 25)